
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `userRoles` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model userRoles
 * 
 */
export type userRolesModel = runtime.Types.Result.DefaultSelection<Prisma.$userRolesPayload>

export type AggregateUserRoles = {
  _count: UserRolesCountAggregateOutputType | null
  _min: UserRolesMinAggregateOutputType | null
  _max: UserRolesMaxAggregateOutputType | null
}

export type UserRolesMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  email: string | null
  role: string | null
}

export type UserRolesMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  email: string | null
  role: string | null
}

export type UserRolesCountAggregateOutputType = {
  id: number
  createdAt: number
  email: number
  role: number
  _all: number
}


export type UserRolesMinAggregateInputType = {
  id?: true
  createdAt?: true
  email?: true
  role?: true
}

export type UserRolesMaxAggregateInputType = {
  id?: true
  createdAt?: true
  email?: true
  role?: true
}

export type UserRolesCountAggregateInputType = {
  id?: true
  createdAt?: true
  email?: true
  role?: true
  _all?: true
}

export type UserRolesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which userRoles to aggregate.
   */
  where?: Prisma.userRolesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of userRoles to fetch.
   */
  orderBy?: Prisma.userRolesOrderByWithRelationInput | Prisma.userRolesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.userRolesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` userRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` userRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned userRoles
  **/
  _count?: true | UserRolesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserRolesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserRolesMaxAggregateInputType
}

export type GetUserRolesAggregateType<T extends UserRolesAggregateArgs> = {
      [P in keyof T & keyof AggregateUserRoles]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserRoles[P]>
    : Prisma.GetScalarType<T[P], AggregateUserRoles[P]>
}




export type userRolesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.userRolesWhereInput
  orderBy?: Prisma.userRolesOrderByWithAggregationInput | Prisma.userRolesOrderByWithAggregationInput[]
  by: Prisma.UserRolesScalarFieldEnum[] | Prisma.UserRolesScalarFieldEnum
  having?: Prisma.userRolesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserRolesCountAggregateInputType | true
  _min?: UserRolesMinAggregateInputType
  _max?: UserRolesMaxAggregateInputType
}

export type UserRolesGroupByOutputType = {
  id: string
  createdAt: Date
  email: string
  role: string
  _count: UserRolesCountAggregateOutputType | null
  _min: UserRolesMinAggregateOutputType | null
  _max: UserRolesMaxAggregateOutputType | null
}

type GetUserRolesGroupByPayload<T extends userRolesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserRolesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserRolesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserRolesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserRolesGroupByOutputType[P]>
      }
    >
  >



export type userRolesWhereInput = {
  AND?: Prisma.userRolesWhereInput | Prisma.userRolesWhereInput[]
  OR?: Prisma.userRolesWhereInput[]
  NOT?: Prisma.userRolesWhereInput | Prisma.userRolesWhereInput[]
  id?: Prisma.StringFilter<"userRoles"> | string
  createdAt?: Prisma.DateTimeFilter<"userRoles"> | Date | string
  email?: Prisma.StringFilter<"userRoles"> | string
  role?: Prisma.StringFilter<"userRoles"> | string
}

export type userRolesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  email?: Prisma.SortOrder
  role?: Prisma.SortOrder
}

export type userRolesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.userRolesWhereInput | Prisma.userRolesWhereInput[]
  OR?: Prisma.userRolesWhereInput[]
  NOT?: Prisma.userRolesWhereInput | Prisma.userRolesWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"userRoles"> | Date | string
  role?: Prisma.StringFilter<"userRoles"> | string
}, "id" | "email">

export type userRolesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  email?: Prisma.SortOrder
  role?: Prisma.SortOrder
  _count?: Prisma.userRolesCountOrderByAggregateInput
  _max?: Prisma.userRolesMaxOrderByAggregateInput
  _min?: Prisma.userRolesMinOrderByAggregateInput
}

export type userRolesScalarWhereWithAggregatesInput = {
  AND?: Prisma.userRolesScalarWhereWithAggregatesInput | Prisma.userRolesScalarWhereWithAggregatesInput[]
  OR?: Prisma.userRolesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.userRolesScalarWhereWithAggregatesInput | Prisma.userRolesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"userRoles"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"userRoles"> | Date | string
  email?: Prisma.StringWithAggregatesFilter<"userRoles"> | string
  role?: Prisma.StringWithAggregatesFilter<"userRoles"> | string
}

export type userRolesCreateInput = {
  id?: string
  createdAt?: Date | string
  email: string
  role: string
}

export type userRolesUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  email: string
  role: string
}

export type userRolesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
}

export type userRolesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
}

export type userRolesCreateManyInput = {
  id?: string
  createdAt?: Date | string
  email: string
  role: string
}

export type userRolesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
}

export type userRolesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
}

export type userRolesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  email?: Prisma.SortOrder
  role?: Prisma.SortOrder
}

export type userRolesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  email?: Prisma.SortOrder
  role?: Prisma.SortOrder
}

export type userRolesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  email?: Prisma.SortOrder
  role?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type userRolesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  email?: boolean
  role?: boolean
}, ExtArgs["result"]["userRoles"]>

export type userRolesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  email?: boolean
  role?: boolean
}, ExtArgs["result"]["userRoles"]>

export type userRolesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  email?: boolean
  role?: boolean
}, ExtArgs["result"]["userRoles"]>

export type userRolesSelectScalar = {
  id?: boolean
  createdAt?: boolean
  email?: boolean
  role?: boolean
}

export type userRolesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "email" | "role", ExtArgs["result"]["userRoles"]>

export type $userRolesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "userRoles"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    email: string
    role: string
  }, ExtArgs["result"]["userRoles"]>
  composites: {}
}

export type userRolesGetPayload<S extends boolean | null | undefined | userRolesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$userRolesPayload, S>

export type userRolesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<userRolesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserRolesCountAggregateInputType | true
  }

export interface userRolesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['userRoles'], meta: { name: 'userRoles' } }
  /**
   * Find zero or one UserRoles that matches the filter.
   * @param {userRolesFindUniqueArgs} args - Arguments to find a UserRoles
   * @example
   * // Get one UserRoles
   * const userRoles = await prisma.userRoles.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends userRolesFindUniqueArgs>(args: Prisma.SelectSubset<T, userRolesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__userRolesClient<runtime.Types.Result.GetResult<Prisma.$userRolesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserRoles that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {userRolesFindUniqueOrThrowArgs} args - Arguments to find a UserRoles
   * @example
   * // Get one UserRoles
   * const userRoles = await prisma.userRoles.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends userRolesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, userRolesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__userRolesClient<runtime.Types.Result.GetResult<Prisma.$userRolesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserRoles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {userRolesFindFirstArgs} args - Arguments to find a UserRoles
   * @example
   * // Get one UserRoles
   * const userRoles = await prisma.userRoles.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends userRolesFindFirstArgs>(args?: Prisma.SelectSubset<T, userRolesFindFirstArgs<ExtArgs>>): Prisma.Prisma__userRolesClient<runtime.Types.Result.GetResult<Prisma.$userRolesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserRoles that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {userRolesFindFirstOrThrowArgs} args - Arguments to find a UserRoles
   * @example
   * // Get one UserRoles
   * const userRoles = await prisma.userRoles.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends userRolesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, userRolesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__userRolesClient<runtime.Types.Result.GetResult<Prisma.$userRolesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserRoles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {userRolesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserRoles
   * const userRoles = await prisma.userRoles.findMany()
   * 
   * // Get first 10 UserRoles
   * const userRoles = await prisma.userRoles.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userRolesWithIdOnly = await prisma.userRoles.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends userRolesFindManyArgs>(args?: Prisma.SelectSubset<T, userRolesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$userRolesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserRoles.
   * @param {userRolesCreateArgs} args - Arguments to create a UserRoles.
   * @example
   * // Create one UserRoles
   * const UserRoles = await prisma.userRoles.create({
   *   data: {
   *     // ... data to create a UserRoles
   *   }
   * })
   * 
   */
  create<T extends userRolesCreateArgs>(args: Prisma.SelectSubset<T, userRolesCreateArgs<ExtArgs>>): Prisma.Prisma__userRolesClient<runtime.Types.Result.GetResult<Prisma.$userRolesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserRoles.
   * @param {userRolesCreateManyArgs} args - Arguments to create many UserRoles.
   * @example
   * // Create many UserRoles
   * const userRoles = await prisma.userRoles.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends userRolesCreateManyArgs>(args?: Prisma.SelectSubset<T, userRolesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserRoles and returns the data saved in the database.
   * @param {userRolesCreateManyAndReturnArgs} args - Arguments to create many UserRoles.
   * @example
   * // Create many UserRoles
   * const userRoles = await prisma.userRoles.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserRoles and only return the `id`
   * const userRolesWithIdOnly = await prisma.userRoles.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends userRolesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, userRolesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$userRolesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserRoles.
   * @param {userRolesDeleteArgs} args - Arguments to delete one UserRoles.
   * @example
   * // Delete one UserRoles
   * const UserRoles = await prisma.userRoles.delete({
   *   where: {
   *     // ... filter to delete one UserRoles
   *   }
   * })
   * 
   */
  delete<T extends userRolesDeleteArgs>(args: Prisma.SelectSubset<T, userRolesDeleteArgs<ExtArgs>>): Prisma.Prisma__userRolesClient<runtime.Types.Result.GetResult<Prisma.$userRolesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserRoles.
   * @param {userRolesUpdateArgs} args - Arguments to update one UserRoles.
   * @example
   * // Update one UserRoles
   * const userRoles = await prisma.userRoles.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends userRolesUpdateArgs>(args: Prisma.SelectSubset<T, userRolesUpdateArgs<ExtArgs>>): Prisma.Prisma__userRolesClient<runtime.Types.Result.GetResult<Prisma.$userRolesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserRoles.
   * @param {userRolesDeleteManyArgs} args - Arguments to filter UserRoles to delete.
   * @example
   * // Delete a few UserRoles
   * const { count } = await prisma.userRoles.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends userRolesDeleteManyArgs>(args?: Prisma.SelectSubset<T, userRolesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {userRolesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserRoles
   * const userRoles = await prisma.userRoles.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends userRolesUpdateManyArgs>(args: Prisma.SelectSubset<T, userRolesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserRoles and returns the data updated in the database.
   * @param {userRolesUpdateManyAndReturnArgs} args - Arguments to update many UserRoles.
   * @example
   * // Update many UserRoles
   * const userRoles = await prisma.userRoles.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserRoles and only return the `id`
   * const userRolesWithIdOnly = await prisma.userRoles.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends userRolesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, userRolesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$userRolesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserRoles.
   * @param {userRolesUpsertArgs} args - Arguments to update or create a UserRoles.
   * @example
   * // Update or create a UserRoles
   * const userRoles = await prisma.userRoles.upsert({
   *   create: {
   *     // ... data to create a UserRoles
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserRoles we want to update
   *   }
   * })
   */
  upsert<T extends userRolesUpsertArgs>(args: Prisma.SelectSubset<T, userRolesUpsertArgs<ExtArgs>>): Prisma.Prisma__userRolesClient<runtime.Types.Result.GetResult<Prisma.$userRolesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {userRolesCountArgs} args - Arguments to filter UserRoles to count.
   * @example
   * // Count the number of UserRoles
   * const count = await prisma.userRoles.count({
   *   where: {
   *     // ... the filter for the UserRoles we want to count
   *   }
   * })
  **/
  count<T extends userRolesCountArgs>(
    args?: Prisma.Subset<T, userRolesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserRolesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRolesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserRolesAggregateArgs>(args: Prisma.Subset<T, UserRolesAggregateArgs>): Prisma.PrismaPromise<GetUserRolesAggregateType<T>>

  /**
   * Group by UserRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {userRolesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends userRolesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: userRolesGroupByArgs['orderBy'] }
      : { orderBy?: userRolesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, userRolesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserRolesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the userRoles model
 */
readonly fields: userRolesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for userRoles.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__userRolesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the userRoles model
 */
export interface userRolesFieldRefs {
  readonly id: Prisma.FieldRef<"userRoles", 'String'>
  readonly createdAt: Prisma.FieldRef<"userRoles", 'DateTime'>
  readonly email: Prisma.FieldRef<"userRoles", 'String'>
  readonly role: Prisma.FieldRef<"userRoles", 'String'>
}
    

// Custom InputTypes
/**
 * userRoles findUnique
 */
export type userRolesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
  /**
   * Filter, which userRoles to fetch.
   */
  where: Prisma.userRolesWhereUniqueInput
}

/**
 * userRoles findUniqueOrThrow
 */
export type userRolesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
  /**
   * Filter, which userRoles to fetch.
   */
  where: Prisma.userRolesWhereUniqueInput
}

/**
 * userRoles findFirst
 */
export type userRolesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
  /**
   * Filter, which userRoles to fetch.
   */
  where?: Prisma.userRolesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of userRoles to fetch.
   */
  orderBy?: Prisma.userRolesOrderByWithRelationInput | Prisma.userRolesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for userRoles.
   */
  cursor?: Prisma.userRolesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` userRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` userRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of userRoles.
   */
  distinct?: Prisma.UserRolesScalarFieldEnum | Prisma.UserRolesScalarFieldEnum[]
}

/**
 * userRoles findFirstOrThrow
 */
export type userRolesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
  /**
   * Filter, which userRoles to fetch.
   */
  where?: Prisma.userRolesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of userRoles to fetch.
   */
  orderBy?: Prisma.userRolesOrderByWithRelationInput | Prisma.userRolesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for userRoles.
   */
  cursor?: Prisma.userRolesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` userRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` userRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of userRoles.
   */
  distinct?: Prisma.UserRolesScalarFieldEnum | Prisma.UserRolesScalarFieldEnum[]
}

/**
 * userRoles findMany
 */
export type userRolesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
  /**
   * Filter, which userRoles to fetch.
   */
  where?: Prisma.userRolesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of userRoles to fetch.
   */
  orderBy?: Prisma.userRolesOrderByWithRelationInput | Prisma.userRolesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing userRoles.
   */
  cursor?: Prisma.userRolesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` userRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` userRoles.
   */
  skip?: number
  distinct?: Prisma.UserRolesScalarFieldEnum | Prisma.UserRolesScalarFieldEnum[]
}

/**
 * userRoles create
 */
export type userRolesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
  /**
   * The data needed to create a userRoles.
   */
  data: Prisma.XOR<Prisma.userRolesCreateInput, Prisma.userRolesUncheckedCreateInput>
}

/**
 * userRoles createMany
 */
export type userRolesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many userRoles.
   */
  data: Prisma.userRolesCreateManyInput | Prisma.userRolesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * userRoles createManyAndReturn
 */
export type userRolesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
  /**
   * The data used to create many userRoles.
   */
  data: Prisma.userRolesCreateManyInput | Prisma.userRolesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * userRoles update
 */
export type userRolesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
  /**
   * The data needed to update a userRoles.
   */
  data: Prisma.XOR<Prisma.userRolesUpdateInput, Prisma.userRolesUncheckedUpdateInput>
  /**
   * Choose, which userRoles to update.
   */
  where: Prisma.userRolesWhereUniqueInput
}

/**
 * userRoles updateMany
 */
export type userRolesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update userRoles.
   */
  data: Prisma.XOR<Prisma.userRolesUpdateManyMutationInput, Prisma.userRolesUncheckedUpdateManyInput>
  /**
   * Filter which userRoles to update
   */
  where?: Prisma.userRolesWhereInput
  /**
   * Limit how many userRoles to update.
   */
  limit?: number
}

/**
 * userRoles updateManyAndReturn
 */
export type userRolesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
  /**
   * The data used to update userRoles.
   */
  data: Prisma.XOR<Prisma.userRolesUpdateManyMutationInput, Prisma.userRolesUncheckedUpdateManyInput>
  /**
   * Filter which userRoles to update
   */
  where?: Prisma.userRolesWhereInput
  /**
   * Limit how many userRoles to update.
   */
  limit?: number
}

/**
 * userRoles upsert
 */
export type userRolesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
  /**
   * The filter to search for the userRoles to update in case it exists.
   */
  where: Prisma.userRolesWhereUniqueInput
  /**
   * In case the userRoles found by the `where` argument doesn't exist, create a new userRoles with this data.
   */
  create: Prisma.XOR<Prisma.userRolesCreateInput, Prisma.userRolesUncheckedCreateInput>
  /**
   * In case the userRoles was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.userRolesUpdateInput, Prisma.userRolesUncheckedUpdateInput>
}

/**
 * userRoles delete
 */
export type userRolesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
  /**
   * Filter which userRoles to delete.
   */
  where: Prisma.userRolesWhereUniqueInput
}

/**
 * userRoles deleteMany
 */
export type userRolesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which userRoles to delete
   */
  where?: Prisma.userRolesWhereInput
  /**
   * Limit how many userRoles to delete.
   */
  limit?: number
}

/**
 * userRoles without action
 */
export type userRolesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userRoles
   */
  select?: Prisma.userRolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the userRoles
   */
  omit?: Prisma.userRolesOmit<ExtArgs> | null
}
